# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    healthcheck:
      test: "exit 0"      

  flyway:
    image: flyway/flyway 
    volumes:
      - ./.migrations:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
    command: -url=jdbc:mysql://db:3306/app -user=root -password=12345

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
  
  website:
    image: nginx:latest
    container_name: website
    volumes:
      - /TextinVoice/public/html:/usr/nginx/html
    ports:
        - 80:80
    restart: always