databaseType = "MySql"
id = "adc86d10-0501-4b7d-bf5c-e90daf8ccae6"
name = "TextinVoice"

[flyway]
locations = ["filesystem:migrations"]
mixed = true
outOfOrder = true
validateMigrationNaming = true

[flyway.check]
majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"